//use only for large text
const String demo = "how are you";

const String appName = "App Name";

const String beginnerTrainerBriefing =
    "A beginner tennis coach is a knowledgeable and enthusiastic individual who introduces newcomers to the fundamentals of tennis. They focus on teaching essential techniques such as proper grip, footwork, and basic strokes like forehand and backhand. The coach helps players develop a solid understanding of the game's rules, scoring system, and court etiquette. Through engaging and supportive instruction, the beginner tennis coach aims to foster a love for the sport while building a foundation for continued skill development.";

const String beginnerTrainerBriefing1 =
    "A beginners tennis coach is a patient and knowledgeable instructor dedicated to introducing individuals to the fundamentals of tennis. With a keen understanding of the unique challenges faced by novice players, this coach creates a supportive and encouraging learning environment to help build a solid foundation in the sport.\nTechnical instruction is a primary focus for the beginners tennis coach. They systematically teach basic techniques such as proper grip, stance, and swing mechanics for essential strokes like forehand and backhand. The coach emphasizes fundamental skills to ensure that players develop a sound and comfortable playing style from the outset.\nCourt awareness and understanding of the game's rules and scoring system are integral components of the beginners tennis coach's instruction. They break down the tennis court into manageable segments, helping players grasp concepts like baseline, service box, and net play. The coach also instills a basic understanding of scoring, game, set, and match rules.\n\nIn addition to technical guidance, the beginners tennis coach introduces basic footwork and movement patterns. Drills and exercises are designed to improve players' agility, balance, and ability to cover the court. The focus is on building confidence in on-court movement and fostering a sense of comfort and control during play.\nBeyond the physical aspects, the beginners tennis coach places emphasis on creating a positive and enjoyable learning experience. They employ engaging teaching methods, incorporating fun drills and games to keep the sessions dynamic and interactive. Positive reinforcement and constructive feedback are key tools used to boost players' confidence and motivation.\nAs players progress, the beginners tennis coach introduces basic strategies, such as court positioning and shot selection. Simple game scenarios and point play may be incorporated to help players understand the flow of a match and make connections between technical skills and strategic decision-making.\n\nThe beginners tennis coach understands the importance of creating a supportive community within the learning environment. They foster camaraderie among players and encourage a sense of sportsmanship and respect on and off the court. The coach may also provide guidance on equipment selection, including choosing the right racket and understanding basic tennis etiquette.\nIn summary, a beginners tennis coach is not only an instructor but also a mentor, helping newcomers develop a love for the sport while building a solid foundation in fundamental techniques, court awareness, and basic strategies. Through patient and positive coaching, they set the stage for players to enjoy the learning process and progress in their tennis journey.";

const String intermediateTrainerBriefing =
    "An intermediate tennis coach is a seasoned instructor with a deep understanding of the sport, specializing in refining the skills of players who have progressed beyond the beginner level. This coach focuses on advancing techniques, enhancing strategy, and improving overall gameplay. They work on developing players' consistency, power, and precision in strokes, as well as introducing more advanced footwork and positioning. The intermediate tennis coach also emphasizes tactical aspects of the game, helping players make strategic decisions and adapt to different playing styles. Through personalized guidance and targeted drills, the coach aims to elevate players to a higher level of proficiency and confidence on the tennis court.";

const String intermediateTrainerBriefing1 =
    "An intermediate tennis coach is a knowledgeable and experienced instructor specializing in guiding players who have progressed beyond the beginner stage and are looking to elevate their game to a more competitive level. This coach possesses a comprehensive understanding of tennis fundamentals and is adept at tailoring instruction to meet the specific needs of players navigating the intermediate skill level.\nTechnical refinement is a key focus of the intermediate tennis coach. They work closely with players to hone and enhance fundamental strokes such as forehand, backhand, volleys, and serves. Attention is given to improving consistency, control, and power, ensuring that players can execute these techniques effectively during matches. The coach may also introduce more advanced shot variations and strategies to expand the player's repertoire.\n\nFootwork and court positioning become more nuanced at the intermediate level, and the coach emphasizes these aspects to enhance players' agility, balance, and ability to cover the court efficiently. Drills and exercises are designed to improve movement patterns, helping players navigate the court with greater ease and precision.\nStrategic development is another critical component of intermediate coaching. The coach collaborates with players to develop a deeper understanding of match tactics, including shot selection, point construction, and court awareness. Players are encouraged to think strategically, adapting their game plan to exploit opponents' weaknesses and capitalize on their own strengths.\nAn intermediate tennis coach also addresses the mental aspects of the game. They assist players in developing focus, concentration, and resilience on the court. Techniques such as visualization, goal-setting, and match simulation may be integrated into training sessions to enhance mental toughness and confidence.\nWhile the intermediate coach provides individualized technical and strategic guidance, they also foster a supportive and motivating training environment. Group drills and match play are incorporated to simulate real-game scenarios, allowing players to practice and apply their skills in a dynamic setting.\n\nIn addition to on-court instruction, the intermediate tennis coach may offer guidance on physical conditioning, fitness routines, and injury prevention to ensure that players are physically prepared for the demands of competitive play. They may also provide insights into equipment selection and overall tennis lifestyle choices.\nOverall, an intermediate tennis coach plays a crucial role in helping players bridge the gap between beginner and advanced levels. Through a combination of technical expertise, strategic insights, and mental coaching, they empower players to refine their skills and develop a well-rounded game, setting the stage for continued improvement and success in competitive tennis.";
const String advancedTrainerBriefing =
    "An advanced tennis coach is a highly skilled and experienced professional dedicated to honing the abilities of seasoned players at an elite level. With a comprehensive understanding of advanced techniques, strategic nuances, and mental resilience, the coach focuses on fine-tuning the skills of top-tier athletes. Training includes refining strokes to perfection, mastering intricate footwork, and developing a sophisticated understanding of match dynamics. The advanced tennis coach also delves into mental conditioning, helping players maintain focus, handle pressure, and strategize effectively during high-stakes competitions. Through meticulous analysis and tailored training regimens, the coach guides elite players toward reaching their peak performance and achieving success at the highest echelons of competitive tennis.";

const String advancedTrainerBriefing1 =
    "An advanced tennis coach is a seasoned and highly specialized professional dedicated to guiding elite players through the intricacies of the sport at the highest levels of competition. Armed with an extensive background in tennis strategy, biomechanics, and psychology, the coach works with athletes who have already achieved a high level of proficiency and aims to refine their skills to the pinnacle of excellence \n The coachs expertise encompasses a deep understanding of advanced techniques across all facets of the game, including groundstrokes, volleys, serves, and specialty shots. They meticulously analyze and fine-tune each players stroke mechanics, ensuring precision, power, and consistency. Advanced footwork drills are designed to enhance agility, court coverage, and the ability to execute complex movements seamlessly.\n\nIn addition to technical mastery, an advanced tennis coach places a strong emphasis on strategic development. They collaborate with players to create tailored game plans, focusing on exploiting opponents weaknesses, adapting to different playing styles, and making split-second decisions during fast-paced matches. Video analysis is often employed to provide players with insights into their strengths and areas for improvement.\nMental fortitude is a key aspect of advanced coaching. The coach works closely with players to cultivate a resilient mindset, teaching them how to manage stress, stay focused under pressure, and maintain peak performance over the course of grueling matches and tournaments. Visualization techniques, mindfulness training, and stress management strategies may be integrated into the coaching regimen.\nThe advanced tennis coach is not only a technical instructor but also a mentor, providing guidance on lifestyle choices, fitness regimens, and recovery practices to ensure that players are physically and mentally prepared for the demands of elite-level competition. The coach often collaborates with a team of specialists, including physiotherapists, nutritionists, and sports psychologists, to optimize the overall well-being and performance of the athlete.\n\nIn summary, an advanced tennis coach is a highly skilled professional who goes beyond refining strokes and strategies. They play a pivotal role in shaping the holistic development of elite players, combining technical expertise, strategic acumen, and mental resilience to help athletes reach their maximum potential on the international tennis stage.";

const String beginner = "Beginner";
const String advanced = "advanced";
const String intermediate = "intermediate";
